<?php

function synch_users_from_external_database_cron() {

	$conn = new mysqli("server", "user", "password", "database");
	if ($conn->connect_error) {
		watchdog ("synch_users_from_external_database","Can't connect to database");
	}
  
	$sql = "SELECT login, localmail FROM synch_users";
	$result = $conn->query($sql);
   
	$queue = DrupalQueue::get('synch_users_from_external_database');
		foreach ($result as $row) {
		watchdog ("synch_users_from_external_database","ROW=".$row["login"]);
		
		// Здесь успешно пишет в журнал
		
		$queue->createItem($row);
	}
}

function synch_users_from_external_database_cron_queue_info() {
	$queues['synch_users_from_external_database'] = array(
		'worker callback' => 'synch_users_from_external_database_callback',
		'time' => 1,
	);
	return $queues;
}

function synch_users_from_external_database_callback($data){
	watchdog ("synch_users_from_external_database","DATA=".$data["login"]);
	
	// Почему то пишет ошибку Notice: Undefined index: login in synch_users_from_external_database_callback()
	
}
